version: "3.8"

services:
  web:
    build: .
    container_name: weather-app-container
    image: brijesh35/my-weather-app:1.0
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000