apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app-1
  ports:
    - protocol: TCP
      port: 8000  # The port on the Service
      targetPort: 8000  # The port on the pods
  type: NodePort
